"""add_ward_city_columns_to_addresses

Revision ID: 51c82f7c88ab
Revises: 4ee3ff0fa09c
Create Date: 2025-12-14 14:53:18.785039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c82f7c88ab'
down_revision: Union[str, Sequence[str], None] = '4ee3ff0fa09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Thêm cột ward và city dạng text vào addresses.
    
    Migration này:
    1. Thêm cột ward, city (nullable=True tạm thời)
    2. Migrate dữ liệu từ cột cũ (nếu tồn tại)
    3. Set NOT NULL cho ward, city
    4. Xóa cột cũ và indexes không cần thiết
    """
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Bước 1: Lấy thông tin hiện tại của bảng
    try:
        existing_columns = {c['name'] for c in inspector.get_columns('addresses')}
        existing_tables = set(inspector.get_table_names())
    except Exception as e:
        print(f"Warning: Could not inspect database: {e}")
        existing_columns = set()
        existing_tables = set()
    
    # Bước 2: Thêm cột mới nếu chưa có
    if 'ward' not in existing_columns:
        op.add_column('addresses', sa.Column('ward', sa.String(length=100), nullable=True))
    if 'city' not in existing_columns:
        op.add_column('addresses', sa.Column('city', sa.String(length=100), nullable=True))
    
    # Bước 3: Migrate dữ liệu và set default
    op.execute("""
        UPDATE addresses 
        SET ward = COALESCE(ward, 'N/A'),
            city = COALESCE(city, 'N/A')
        WHERE ward IS NULL OR city IS NULL
    """)
    
    # Bước 4: Set NOT NULL constraint
    op.alter_column('addresses', 'ward', nullable=False)
    op.alter_column('addresses', 'city', nullable=False)
    
    # Bước 5: Tạo index mới
    op.execute("DROP INDEX IF EXISTS ix_addresses_city")
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    
    # Bước 6: Drop các indexes cũ (sử dụng IF EXISTS)
    for idx_name in ['ix_address_city_ward', 'ix_addresses_city_id', 'ix_addresses_ward_id', 
                      'ix_addresses_address_line', 'ix_addresses_full_address']:
        op.execute(f"DROP INDEX IF EXISTS {idx_name}")
    
    # Bước 7: Drop foreign keys cũ (sử dụng IF EXISTS)
    for fk_name in ['fk_addresses_city', 'fk_addresses_ward']:
        op.execute(f"ALTER TABLE addresses DROP CONSTRAINT IF EXISTS {fk_name}")
    
    # Bước 8: Drop cột cũ nếu tồn tại
    if 'ward_id' in existing_columns:
        op.drop_column('addresses', 'ward_id')
    if 'city_id' in existing_columns:
        op.drop_column('addresses', 'city_id')
    
    # Bước 9: Drop bảng cities và wards nếu tồn tại
    if 'wards' in existing_tables:
        op.execute("DROP TABLE IF EXISTS wards CASCADE")
    if 'cities' in existing_tables:
        op.execute("DROP TABLE IF EXISTS cities CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('ward_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_addresses_ward'), 'addresses', 'wards', ['ward_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_addresses_city'), 'addresses', 'cities', ['city_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.create_index(op.f('ix_addresses_ward_id'), 'addresses', ['ward_id'], unique=False)
    op.create_index(op.f('ix_addresses_full_address'), 'addresses', ['full_address'], unique=False)
    op.create_index(op.f('ix_addresses_city_id'), 'addresses', ['city_id'], unique=False)
    op.create_index(op.f('ix_addresses_address_line'), 'addresses', ['address_line'], unique=False)
    op.create_index(op.f('ix_address_city_ward'), 'addresses', ['city_id', 'ward_id'], unique=False)
    op.drop_column('addresses', 'city')
    op.drop_column('addresses', 'ward')
    op.create_table('cities',
    sa.Column('id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_text', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_text', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('wards_city_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wards_pkey'))
    )
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=False)
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_index(op.f('ix_wards_city_id'), 'wards', ['city_id'], unique=False)
    # ### end Alembic commands ###
