"""add_gender_to_user

Revision ID: 64571fa96173
Revises: 51c82f7c88ab
Create Date: 2025-12-17 09:00:24.420460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64571fa96173'
down_revision: Union[str, Sequence[str], None] = '51c82f7c88ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Thêm cột gender với nullable=True trước, sau đó update giá trị mặc định
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    
    # Update tất cả user hiện tại với giá trị mặc định "Nam"
    op.execute("UPDATE users SET gender = 'Nam' WHERE gender IS NULL")
    
    # Sau đó mới set NOT NULL
    op.alter_column('users', 'gender', nullable=False, server_default='Nam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
