"""add_display_name_to_roles

Revision ID: 9a17cfe3e9da
Revises: f544281ab27c
Create Date: 2025-12-17 10:28:49.425364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a17cfe3e9da'
down_revision: Union[str, Sequence[str], None] = 'f544281ab27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'display_name')
    # ### end Alembic commands ###
