"""add_initial_electricity_index_to_contracts

Revision ID: 004198707da7
Revises: a7fd251f5cbf
Create Date: 2025-12-25 15:18:15.220895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004198707da7'
down_revision: Union[str, Sequence[str], None] = 'a7fd251f5cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('initial_electricity_index', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'initial_electricity_index')
    # ### end Alembic commands ###
