"""Make uploaded_by nullable in room_photos

Revision ID: 01b690237671
Revises: 3c3d5bc73197
Create Date: 2025-12-21 15:14:52.309746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b690237671'
down_revision: Union[str, Sequence[str], None] = '3c3d5bc73197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_photos', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('room_types_name_key'), 'room_types', type_='unique')
    op.drop_index(op.f('ix_room_types_name'), table_name='room_types')
    op.create_index(op.f('ix_room_types_name'), 'room_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_types_name'), table_name='room_types')
    op.create_index(op.f('ix_room_types_name'), 'room_types', ['name'], unique=False)
    op.create_unique_constraint(op.f('room_types_name_key'), 'room_types', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('room_photos', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
