"""add relative info to user

Revision ID: 42e0836d22d6
Revises: edf90b661fa0
Create Date: 2025-12-19 18:51:18.622888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e0836d22d6'
down_revision: Union[str, Sequence[str], None] = 'edf90b661fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('relative_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('relative_phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'relative_phone')
    op.drop_column('users', 'relative_name')
    # ### end Alembic commands ###
