"""Add image_base64 column to room_photos table

Revision ID: 4ee3ff0fa09c
Revises: a1f4835d0e74
Create Date: 2025-12-11 16:22:18.550714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee3ff0fa09c'
down_revision: Union[str, Sequence[str], None] = 'a1f4835d0e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contract_documents_contract_id_fkey'), 'contract_documents', type_='foreignkey')
    op.create_foreign_key(None, 'contract_documents', 'contracts', ['contract_id'], ['id'])
    op.drop_constraint(op.f('invoices_contract_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'contracts', ['contract_id'], ['id'])
    op.drop_constraint(op.f('reviews_contract_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'contracts', ['contract_id'], ['id'])
    op.add_column('room_photos', sa.Column('image_base64', sa.Text(), nullable=True))
    op.alter_column('room_photos', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('room_photos', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('room_photos', 'image_base64')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_contract_id_fkey'), 'reviews', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_contract_id_fkey'), 'invoices', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'contract_documents', type_='foreignkey')
    op.create_foreign_key(op.f('contract_documents_contract_id_fkey'), 'contract_documents', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
