"""add_display_name_to_roles

Revision ID: 58e08dc8c28e
Revises: 9a17cfe3e9da
Create Date: 2025-12-17 10:29:18.568066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e08dc8c28e'
down_revision: Union[str, Sequence[str], None] = '9a17cfe3e9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
