"""remove_invoice_id_use_id_directly

Revision ID: 6b70aef8e183
Revises: 9545a97567f2
Create Date: 2025-12-24 23:02:49.249786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b70aef8e183'
down_revision: Union[str, Sequence[str], None] = '9545a97567f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
    
    Thay đổi FK từ invoices.invoice_id sang invoices.id.
    Cần xóa FK trước, update dữ liệu, xóa cột, rồi tạo FK mới.
    """
    # 1. Drop FK constraints cũ TRƯỚC
    op.drop_constraint('payments_invoice_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('invoice_proofs_invoice_id_fkey', 'invoice_proofs', type_='foreignkey')
    
    # 2. Cập nhật dữ liệu payments: invoice_id cũ -> id tương ứng của invoice
    op.execute("""
        UPDATE payments p
        SET invoice_id = i.id
        FROM invoices i
        WHERE p.invoice_id = i.invoice_id
    """)
    
    # 3. Cập nhật dữ liệu invoice_proofs: invoice_id cũ -> id tương ứng
    op.execute("""
        UPDATE invoice_proofs ip
        SET invoice_id = i.id
        FROM invoices i
        WHERE ip.invoice_id = i.invoice_id
    """)
    
    # 4. Drop index và cột invoice_id trên invoices
    op.drop_index('ix_invoices_invoice_id', table_name='invoices')
    op.drop_column('invoices', 'invoice_id')
    
    # 5. Tạo FK mới trỏ đến invoices.id
    op.create_foreign_key('payments_invoice_id_fkey', 'payments', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('invoice_proofs_invoice_id_fkey', 'invoice_proofs', 'invoices', ['invoice_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_invoice_id_fkey'), 'payments', 'invoices', ['invoice_id'], ['invoice_id'])
    op.add_column('invoices', sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=True)
    op.drop_constraint(None, 'invoice_proofs', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_proofs_invoice_id_fkey'), 'invoice_proofs', 'invoices', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###
