"""increase_room_decimal_precision

Revision ID: c2e2bcac9ae5
Revises: 6b70aef8e183
Create Date: 2025-12-25 14:49:33.827463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e2bcac9ae5'
down_revision: Union[str, Sequence[str], None] = '6b70aef8e183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('rooms', 'electricity_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('rooms', 'water_price_per_person',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('rooms', 'deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'deposit_amount',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('rooms', 'water_price_per_person',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('rooms', 'electricity_price',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('rooms', 'base_price',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
