"""create noti

Revision ID: d8480d7c0168
Revises: 9bd03f541fb0
Create Date: 2025-12-23 22:03:19.149054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8480d7c0168'
down_revision: Union[str, Sequence[str], None] = '9bd03f541fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('termination_requester_id', sa.UUID(), nullable=True))
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'contracts', 'users', ['termination_requester_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.alter_column('contracts', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('contracts', 'termination_requester_id')
    # ### end Alembic commands ###
