"""add_service_fees_json_to_contract

Revision ID: f544281ab27c
Revises: e86dc25b71b7
Create Date: 2025-12-17 09:49:44.775898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f544281ab27c'
down_revision: Union[str, Sequence[str], None] = 'e86dc25b71b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('payment_cycle_months', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('electricity_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('contracts', sa.Column('water_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('contracts', sa.Column('service_fees', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'service_fees')
    op.drop_column('contracts', 'water_price')
    op.drop_column('contracts', 'electricity_price')
    op.drop_column('contracts', 'payment_cycle_months')
    # ### end Alembic commands ###
